# Generated by Django 5.2.8 on 2025-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок поста", max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите содержимое поста", null=True, verbose_name="Содержимое"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blogs/image",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Укажите дату создания", verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_publication",
                    models.BooleanField(
                        default=True, help_text="Укажите признак публикации", verbose_name="Признак публикации"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост блога",
                "verbose_name_plural": "Посты блога",
                "ordering": ["title"],
            },
        ),
    ]
