# Generated by Django 5.2.8 on 2025-12-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["created_at", "title"],
                "verbose_name": "Пост блога",
                "verbose_name_plural": "Посты блога",
            },
        ),
    ]
