# Generated by Django 5.2.8 on 2025-12-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(
                default=False, help_text="Укажите статус публикации", verbose_name="Статус публикации"
            ),
        ),
    ]
