# Generated by Django 5.2.8 on 2025-12-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_is_publication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [("can_unpublish_product", "Отмена публикации продукта")],
                "verbose_name": "Продкут",
                "verbose_name_plural": "Продкуты",
            },
        ),
    ]
